# -*- coding: utf-8 -*-
"""Day3 assighnment b7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1SnJckVrsKbEB-WLEURBLus-egYitILJz
"""

#Day3 Assighnmet 1

al=int(input("Enter the altitude you are in:"))
 
 
if al <= 1000 :
    print("It is safe to land")
elif al <= 5000 :
    print("Come down to altitude 1000ft")
else:
    print("Turn around and try again")

#day 3 assignhment 2

print("Prime numbers between 1 to 200 are:")
 
for i in range(2,200):
     for j in range(2,i):
         if(i%j==0):
             break
        
     else:
              print(i)



